spring:
  profiles: aws

  datasource:
    #    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    #    username: sa
    #    password:
    #    driver-class-name: org.h2.Driver

    url: jdbc:mariadb://spring-boot-rds.cwoiknsupemn.us-east-2.rds.amazonaws.com/spring_boot?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: alasheep
    password: 19451945

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace