spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#    jdbc-url: jdbc:mariadb://rds-mariadb.ch4ipcxitqs1.ap-northeast-2.rds.amazonaws.com:3306/wickies?useUnicode=yes&characterEncoding=UTF-8
    url: jdbc:mariadb://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: alasheep
    password: 1945

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace